/****** Object:  Procedure [dbo].[Web_Account_OgItemHistory_old]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [dbo].[Web_Account_OgItemHistory_old]
	-- Add the parameters for the stored procedure here
	@ARDivisionNo char(2)='00',
	@Customer varchar(9),
	@ItemCode varchar(15)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
WITH LASTORDERED AS
(
    -- Insert statements for procedure here
	SELECT     ROW_NUMBER() OVER (PARTITION BY MAS_POL.dbo.CI_ITEM.ITEMCODE ORDER BY MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE desc) AS 'RN',
			   MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE as LastInvoiceDate, SUM(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.QUANTITYSHIPPED) AS LastQuantityShipped, 
                      MIN(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.UNITPRICE) AS LastPrice
FROM         MAS_POL.dbo.CI_ITEM LEFT OUTER JOIN
                      MAS_POL.dbo.AR_INVOICEHISTORYDETAIL LEFT OUTER JOIN
                      MAS_POL.dbo.AR_INVOICEHISTORYHEADER ON MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.INVOICENO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICENO AND 
                      MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.HEADERSEQNO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.HEADERSEQNO ON 
                      MAS_POL.dbo.CI_ITEM.ITEMCODE = MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.ITEMCODE
WHERE     MAS_POL.dbo.CI_ITEM.ITEMCODE=@ItemCode and MAS_POL.dbo.AR_INVOICEHISTORYHEADER.CUSTOMERNO=@Customer and MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDivisionNo=@ARDivisionNo AND MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE >= DATEADD(YEAR, - 2, GETDATE()) AND MAS_POL.dbo.AR_INVOICEHISTORYHEADER.MODULECODE = 'S/O'
GROUP BY MAS_POL.dbo.CI_ITEM.ITEMCODE, MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE
                     
HAVING SUM(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.QUANTITYSHIPPED)>0
)
SELECT LastInvoiceDate,LastQuantityShipped,LastPrice
	FROM LASTORDERED
	WHERE RN = 1
END
