/****** Object:  Table [dbo].[IM_BOTTLE_SIZES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[IM_BOTTLE_SIZES](
	[BOTTLE_SIZE] [nchar](10) NOT NULL,
	[PRIORITY] [int] NOT NULL
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE CLUSTERED INDEX [IM_BottleSize] ON [dbo].[IM_BOTTLE_SIZES]
(
	[BOTTLE_SIZE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
