/****** Object:  Table [dbo].[SO_SalesOrderDetail_ss]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SO_SalesOrderDetail_ss](
	[SalesOrderNo] [varchar](7) NOT NULL,
	[LineKey] [varchar](6) NOT NULL,
	[LineSeqNo] [varchar](14) NULL,
	[ItemCode] [varchar](30) NULL,
	[ItemType] [varchar](1) NULL,
	[ItemCodeDesc] [varchar](30) NULL,
	[ExtendedDescriptionKey] [varchar](10) NULL,
	[Discount] [varchar](1) NULL,
	[Commissionable] [varchar](1) NULL,
	[SubjectToExemption] [varchar](1) NULL,
	[WarehouseCode] [varchar](3) NULL,
	[PriceLevel] [varchar](1) NULL,
	[MasterOrderLineKey] [varchar](6) NULL,
	[UnitOfMeasure] [varchar](4) NULL,
	[DropShip] [varchar](1) NULL,
	[PrintDropShipment] [varchar](1) NULL,
	[SalesKitLineKey] [varchar](6) NULL,
	[CostOfGoodsSoldAcctKey] [varchar](9) NULL,
	[SalesAcctKey] [varchar](9) NULL,
	[PriceOverridden] [varchar](1) NULL,
	[ExplodedKitItem] [varchar](1) NULL,
	[StandardKitBill] [varchar](1) NULL,
	[Revision] [varchar](3) NULL,
	[BillOption1] [varchar](2) NULL,
	[BillOption2] [varchar](2) NULL,
	[BillOption3] [varchar](2) NULL,
	[BillOption4] [varchar](2) NULL,
	[BillOption5] [varchar](2) NULL,
	[BillOption6] [varchar](2) NULL,
	[BillOption7] [varchar](2) NULL,
	[BillOption8] [varchar](2) NULL,
	[BillOption9] [varchar](2) NULL,
	[BackorderKitCompLine] [varchar](1) NULL,
	[SkipPrintCompLine] [varchar](1) NULL,
	[PromiseDate] [datetime] NOT NULL,
	[AliasItemNo] [varchar](30) NULL,
	[SOHistoryDetlSeqNo] [varchar](14) NULL,
	[TaxClass] [varchar](2) NULL,
	[CustomerAction] [varchar](1) NULL,
	[ItemAction] [varchar](1) NULL,
	[WarrantyCode] [varchar](10) NULL,
	[ExpirationDate] [datetime] NOT NULL,
	[ExpirationOverridden] [varchar](1) NULL,
	[CostOverridden] [varchar](1) NULL,
	[CostCode] [varchar](9) NULL,
	[CostType] [varchar](1) NULL,
	[CommentText] [varchar](2048) NULL,
	[QuantityOrdered] [decimal](15, 6) NULL,
	[QuantityShipped] [decimal](15, 6) NULL,
	[QuantityBackordered] [decimal](15, 6) NULL,
	[MasterOriginalQty] [decimal](15, 6) NULL,
	[MasterQtyBalance] [decimal](15, 6) NULL,
	[MasterQtyOrderedToDate] [decimal](15, 6) NULL,
	[RepeatingQtyShippedToDate] [decimal](15, 6) NULL,
	[UnitPrice] [decimal](15, 6) NULL,
	[UnitCost] [decimal](15, 6) NULL,
	[ExtensionAmt] [decimal](11, 2) NULL,
	[UnitOfMeasureConvFactor] [decimal](11, 4) NULL,
	[QuantityPerBill] [decimal](15, 6) NULL,
	[LineDiscountPercent] [decimal](8, 3) NULL,
	[UDF_RESTRICT_ALLOCATED] [varchar](1) NULL,
	[UDF_RESTRICT_MANAGER] [varchar](15) NULL,
	[UDF_RESTRICT_MAX] [decimal](10, 2) NULL,
	[UDF_RESTRICT_NORETAIL] [varchar](1) NULL,
	[UDF_RESTRICT_OFFSALE] [varchar](1) NULL,
	[UDF_RESTRICT_STATE] [varchar](12) NULL,
	[UDF_IO_LINENUMBER] [decimal](7, 0) NULL,
	[UDF_VALUATION] [varchar](1) NULL,
	[UDF_RESTRICT_OFFSALE_NOTES] [varchar](15) NULL,
	[Valuation] [varchar](1) NULL,
	[LotSerialFullyDistributed] [varchar](1) NULL,
	[APDivisionNo] [varchar](2) NULL,
	[VendorNo] [varchar](7) NULL,
	[PurchaseOrderNo] [varchar](7) NULL,
	[PurchaseOrderRequiredDate] [datetime] NOT NULL,
	[LineWeight] [decimal](11, 2) NULL,
	[CommodityCode] [varchar](12) NULL,
	[AlternateTaxIdentifier] [varchar](15) NULL,
	[TaxTypeApplied] [varchar](4) NULL,
	[NetGrossIndicator] [varchar](1) NULL,
	[DebitCreditIndicator] [varchar](1) NULL,
	[TaxAmt] [decimal](11, 2) NULL,
	[TaxRate] [decimal](10, 6) NULL
) ON [PRIMARY]
