/****** Object:  Table [dbo].[SO_SalesOrderHeader_ss]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SO_SalesOrderHeader_ss](
	[SalesOrderNo] [varchar](7) NOT NULL,
	[OrderDate] [datetime] NOT NULL,
	[OrderType] [varchar](1) NULL,
	[OrderStatus] [varchar](1) NULL,
	[MasterRepeatingOrderNo] [varchar](7) NULL,
	[ShipExpireDate] [datetime] NOT NULL,
	[ARDivisionNo] [varchar](2) NULL,
	[CustomerNo] [varchar](20) NULL,
	[BillToName] [varchar](30) NULL,
	[BillToAddress1] [varchar](30) NULL,
	[BillToAddress2] [varchar](30) NULL,
	[BillToAddress3] [varchar](30) NULL,
	[BillToCity] [varchar](20) NULL,
	[BillToState] [varchar](2) NULL,
	[BillToZipCode] [varchar](10) NULL,
	[BillToCountryCode] [varchar](3) NULL,
	[ShipToCode] [varchar](4) NULL,
	[ShipToName] [varchar](30) NULL,
	[ShipToAddress1] [varchar](30) NULL,
	[ShipToAddress2] [varchar](30) NULL,
	[ShipToAddress3] [varchar](30) NULL,
	[ShipToCity] [varchar](20) NULL,
	[ShipToState] [varchar](2) NULL,
	[ShipToZipCode] [varchar](10) NULL,
	[ShipToCountryCode] [varchar](3) NULL,
	[ShipVia] [varchar](15) NULL,
	[ShipZone] [varchar](5) NULL,
	[ShipZoneActual] [varchar](5) NULL,
	[ShipWeight] [varchar](5) NULL,
	[CustomerPONo] [varchar](30) NULL,
	[FOB] [varchar](15) NULL,
	[WarehouseCode] [varchar](3) NULL,
	[ConfirmTo] [varchar](30) NULL,
	[Comment] [varchar](30) NULL,
	[TermsCode] [varchar](2) NULL,
	[TaxSchedule] [varchar](9) NULL,
	[TaxExemptNo] [varchar](15) NULL,
	[InvalidTaxCalc] [varchar](1) NULL,
	[PrintSalesOrders] [varchar](1) NULL,
	[PrintPickingSheets] [varchar](1) NULL,
	[LastInvoiceOrderDate] [datetime] NOT NULL,
	[LastInvoiceOrderNo] [varchar](7) NULL,
	[CurrentInvoiceNo] [varchar](7) NULL,
	[CheckNoForDeposit] [varchar](10) NULL,
	[CycleCode] [varchar](2) NULL,
	[FaxNo] [varchar](17) NULL,
	[BatchFax] [varchar](1) NULL,
	[BatchEmail] [varchar](1) NULL,
	[EmailAddress] [varchar](250) NULL,
	[FreightCalculationMethod] [varchar](1) NULL,
	[LotSerialLinesExist] [varchar](1) NULL,
	[SalespersonDivisionNo] [varchar](2) NULL,
	[SalespersonNo] [varchar](4) NULL,
	[SplitCommissions] [varchar](1) NULL,
	[SalespersonDivisionNo2] [varchar](2) NULL,
	[SalespersonNo2] [varchar](4) NULL,
	[SalespersonDivisionNo3] [varchar](2) NULL,
	[SalespersonNo3] [varchar](4) NULL,
	[SalespersonDivisionNo4] [varchar](2) NULL,
	[SalespersonNo4] [varchar](4) NULL,
	[SalespersonDivisionNo5] [varchar](2) NULL,
	[SalespersonNo5] [varchar](4) NULL,
	[EBMUserType] [varchar](1) NULL,
	[EBMSubmissionType] [varchar](1) NULL,
	[EBMUserIDSubmittingThisOrder] [varchar](15) NULL,
	[PaymentType] [varchar](5) NULL,
	[OtherPaymentTypeRefNo] [varchar](24) NULL,
	[CancelReasonCode] [varchar](5) NULL,
	[PaymentTypeCategory] [varchar](1) NULL,
	[RMANo] [varchar](7) NULL,
	[JobNo] [varchar](7) NULL,
	[ResidentialAddress] [varchar](1) NULL,
	[TaxableSubjectToDiscount] [decimal](12, 2) NULL,
	[NonTaxableSubjectToDiscount] [decimal](12, 2) NULL,
	[TaxSubjToDiscPrcntOfTotSubjTo] [decimal](6, 2) NULL,
	[DiscountRate] [decimal](7, 3) NULL,
	[DiscountAmt] [decimal](11, 2) NULL,
	[TaxableAmt] [decimal](12, 2) NULL,
	[NonTaxableAmt] [decimal](12, 2) NULL,
	[SalesTaxAmt] [decimal](11, 2) NULL,
	[Weight] [decimal](11, 2) NULL,
	[FreightAmt] [decimal](11, 2) NULL,
	[DepositAmt] [decimal](12, 2) NULL,
	[CommissionRate] [decimal](8, 3) NULL,
	[SplitCommRate2] [decimal](8, 3) NULL,
	[SplitCommRate3] [decimal](8, 3) NULL,
	[SplitCommRate4] [decimal](8, 3) NULL,
	[SplitCommRate5] [decimal](8, 3) NULL,
	[NumberOfShippingLabels] [decimal](3, 0) NULL,
	[LastNoOfShippingLabels] [decimal](3, 0) NULL,
	[DateCreated] [datetime] NOT NULL,
	[TimeCreated] [varchar](8) NULL,
	[UserCreatedKey] [varchar](10) NULL,
	[DateUpdated] [datetime] NOT NULL,
	[TimeUpdated] [varchar](8) NULL,
	[UserUpdatedKey] [varchar](10) NULL,
	[CRMUserID] [varchar](11) NULL,
	[CRMPersonID] [varchar](11) NULL,
	[CRMOpportunityID] [varchar](11) NULL,
	[CRMCompanyID] [varchar](11) NULL,
	[CRMProspectID] [varchar](11) NULL,
	[UDF_ARRIVAL_DATE] [datetime] NULL,
	[UDF_REGION_CODE] [varchar](10) NULL,
	[UDF_COD_CONFIRMED] [varchar](1) NULL,
	[UDF_NJ_COOP] [varchar](10) NULL,
	[UDF_SPECIAL_INSTRUCTIONS] [varchar](1) NULL,
	[UDF_SPECIAL_INST_TEXT] [varchar](100) NULL,
	[UDF_ACCT_OVERRIDE_HDR] [varchar](10) NULL,
	[UDF_DELIVERY_FRI] [varchar](1) NULL,
	[UDF_DELIVERY_MON] [varchar](1) NULL,
	[UDF_DELIVERY_THURS] [varchar](1) NULL,
	[UDF_DELIVERY_TUES] [varchar](1) NULL,
	[UDF_DELIVERY_WED] [varchar](1) NULL,
	[UDF_COOP_CASES] [decimal](7, 0) NULL,
	[UDF_CREDITHOLD] [varchar](1) NULL,
	[UDF_CREDITLIMIT] [decimal](10, 2) NULL,
	[UDF_CURRENTBALANCE] [decimal](10, 2) NULL,
	[UDF_OPENORDERAMT] [decimal](10, 2) NULL,
	[UDF_PRICELEVEL] [varchar](1) NULL,
	[UDF_SHIPMETHOD] [varchar](15) NULL,
	[UDF_NOTES_LOS] [varchar](150) NULL,
	[UDF_PO_REQUIRED] [varchar](1) NULL,
	[UDF_COOP_LIST] [varchar](20) NULL,
	[UDF_WAIVE_CHARGES] [varchar](1) NULL,
	[UDF_CUSTOMERTYPE] [varchar](4) NULL,
	[UDF_REVIEW_COOP] [varchar](1) NULL,
	[UDF_REVIEW_CREDIT] [varchar](1) NULL,
	[UDF_REVIEW_NOTES] [varchar](1) NULL,
	[UDF_REVIEW_PO] [varchar](1) NULL,
	[UDF_REVIEW_RESTRICTIONS] [varchar](1) NULL,
	[UDF_REVIEW_NSQTY] [varchar](1) NULL,
	[UDF_CERT_ON_FILE] [varchar](1) NULL,
	[UDF_CUST_ACTIVE_STAT] [varchar](1) NULL,
	[UDF_LIC_EXPIRATION] [datetime] NULL,
	[UDF_LIST_CREDIT] [varchar](50) NULL,
	[UDF_LIST_NSQTY] [varchar](50) NULL,
	[UDF_LIST_RESTRICTIONS] [varchar](500) NULL,
	[UDF_CORP_NAME] [varchar](35) NULL,
	[UDF_CUSTOMERNAME] [varchar](30) NULL,
	[UDF_LICENSE_NUM] [varchar](20) NULL,
	[UDF_REVIEW_DNT] [varchar](1) NULL,
	[UDF_LIST_MOBO] [varchar](150) NULL,
	[BillToDivisionNo] [varchar](2) NULL,
	[BillToCustomerNo] [varchar](20) NULL,
	[SalesOrderPrinted] [varchar](1) NULL,
	[PickingSheetPrinted] [varchar](1) NULL,
	[UDF_INSTRUCTIONS] [varchar](100) NULL,
	[UDF_TERRITORY] [varchar](25) NULL,
	[UDF_GUARANTEED_AM] [varchar](1) NULL,
	[UDF_GUARANTEED_AM_CUSTOMER] [varchar](1) NULL,
	[UDF_PERM_INSTRUCTIONS] [varchar](1) NULL,
	[UDF_IS_BH] [varchar](1) NULL,
	[PromotedDate] [datetime] NOT NULL,
	[UDF_IS_BH_HOLD] [varchar](1) NULL,
	[UDF_CHECK_REQUIRED] [varchar](1) NULL,
	[UDF_ORDER_ID] [varchar](50) NULL,
	[UDF_REVIEW_PA] [varchar](1) NULL
) ON [PRIMARY]
