/****** Object:  Table [dbo].[WebSiteExportData_Previous_Lambda]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE TABLE dbo.WebSiteExportData_Previous_Lambda(
	[Item Code] [varchar](30) NULL,
	[Vendor] [varchar](78) NULL,
	[Description] [varchar](136) NULL,
	[Vintage] [varchar](4) NULL,
	[Bottle Sizes] [nvarchar](max) NULL,
	[Country] [varchar](25) NULL,
	[Region] [varchar](25) NOT NULL,
	[Appellation] [varchar](50) NOT NULL,
	[Wine Type] [varchar](20) NULL,
	[Varietals] [varchar](25) NOT NULL,
	[Varietal Notes] [varchar](max) NOT NULL,
	[Organic] [varchar](10) NULL,
	[Biodynamic] [varchar](10) NULL,
	[Ratings - Wine Advocate] [varchar](20) NULL,
	[Ratings - Wine Spectator] [varchar](20) NULL,
	[Ratings - IWC] [varchar](20) NULL,
	[Ratings - Burghound] [varchar](20) NULL,
	[Ratings - Antonio Galloni] [varchar](20) NULL,
	[Ratings - Other] [varchar](20) NULL,
	[Review - Wine Advocate] [varchar](max) NOT NULL,
	[Review - Wine Spectator] [varchar](max) NOT NULL,
	[Review - IWC] [varchar](max) NOT NULL,
	[Review - Burghound] [varchar](max) NOT NULL,
	[Review - Antonio Galloni] [varchar](max) NOT NULL,
	[Review - Other] [varchar](max) NOT NULL,
	[Notes - Vineyard] [varchar](max) NOT NULL,
	[Notes - Orientation] [varchar](max) NOT NULL,
	[Notes - Soil] [varchar](max) NOT NULL,
	[Notes - Viticulture] [varchar](max) NOT NULL,
	[Notes - Vinification] [varchar](max) NOT NULL,
	[Notes - Aging Process] [varchar](max) NOT NULL,
	[Notes - Production] [varchar](max) NOT NULL,
	[Notes - Tasting] [varchar](max) NOT NULL,
	[ImageFile] [varchar](30) NULL,
	[Natural] [varchar](1) NOT NULL,
	[Regen] [varchar](1) NOT NULL,
	[Vegan] [varchar](1) NOT NULL,
	[HauteValeur] [varchar](1) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
