/****** Object:  View [dbo].[AR_CUSTOMER_LICENSE]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[AR_CUSTOMER_LICENSE]
AS
SELECT     CUSTOMERNO, ARDIVISIONNO, LEFT(UDF_LICENSE_NUM, 11) AS License, TERMSCODE, CREDITHOLD, UDF_CREDIT_STATUS, UDF_CERT_ON_FILE
FROM         MAS_POL.dbo.AR_CUSTOMER
WHERE UDF_CUST_ACTIVE_STAT='Y'
