/****** Object:  View [dbo].[BO_InventoryHeld_800]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[BO_InventoryHeld_800]
AS
SELECT     MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMCODE, Sum(
						MAS_POL.dbo.SO_SALESORDERDETAIL.QUANTITYORDERED
						) as QuantityHeld
FROM         MAS_POL.dbo.SO_SALESORDERHEADER INNER JOIN
                      MAS_POL.dbo.SO_SALESORDERDETAIL ON MAS_POL.dbo.SO_SALESORDERHEADER.SALESORDERNO = MAS_POL.dbo.SO_SALESORDERDETAIL.SALESORDERNO       
WHERE  MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMTYPE='1' and MAS_POL.dbo.SO_SALESORDERDETAIL.WAREHOUSECODE='800' and (MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='BO' or MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='AL')
GROUP BY MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMCODE
