/****** Object:  View [dbo].[COD_ALL]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[COD_ALL]
AS
SELECT     dbo.AR_CUSTOMER_LICENSE.ARDIVISIONNO, dbo.AR_CUSTOMER_LICENSE.CUSTOMERNO, dbo.AR_CUSTOMER_LICENSE.License AS License_POL, 
                      dbo.COD_NY.License AS License_NY, dbo.COD_NJ.License AS License_NJ, 'TermsCode'=
						Case
							When (dbo.COD_NJ.License=dbo.AR_CUSTOMER_LICENSE.License OR dbo.COD_NY.License=dbo.AR_CUSTOMER_LICENSE.License) and (dbo.AR_CUSTOMER_LICENSE.TERMSCODE='00' or dbo.AR_CUSTOMER_LICENSE.TERMSCODE='30') then '00'
							When dbo.AR_CUSTOMER_LICENSE.TERMSCODE='00' Then '30'
							Else dbo.AR_CUSTOMER_LICENSE.TERMSCODE
						End,
						'CreditHold'=
						Case
							When ((dbo.COD_NJ.License=dbo.AR_CUSTOMER_LICENSE.License OR dbo.COD_NY.License=dbo.AR_CUSTOMER_LICENSE.License) and (dbo.AR_CUSTOMER_LICENSE.TERMSCODE='00' or dbo.AR_CUSTOMER_LICENSE.TERMSCODE='30')) or dbo.AR_CUSTOMER_LICENSE.UDF_CREDIT_STATUS='Exp Lisc' or dbo.AR_CUSTOMER_LICENSE.UDF_CERT_ON_FILE='N' or dbo.AR_CUSTOMER_LICENSE.TERMSCODE='05' or dbo.AR_CUSTOMER_LICENSE.TERMSCODE='10' or dbo.AR_CUSTOMER_LICENSE.TERMSCODE='95' then 'Y'
							When dbo.AR_CUSTOMER_LICENSE.TERMSCODE='00' OR dbo.AR_CUSTOMER_LICENSE.TERMSCODE='30' Then 'N'
							Else dbo.AR_CUSTOMER_LICENSE.CREDITHOLD
						End
FROM         dbo.AR_CUSTOMER_LICENSE LEFT OUTER JOIN
                      dbo.COD_NJ ON dbo.AR_CUSTOMER_LICENSE.License = dbo.COD_NJ.License LEFT OUTER JOIN
                      dbo.COD_NY ON dbo.AR_CUSTOMER_LICENSE.License = dbo.COD_NY.License
WHERE		 dbo.AR_CUSTOMER_LICENSE.ARDIVISIONNO  = '00'  and (dbo.AR_CUSTOMER_LICENSE.UDF_CREDIT_STATUS='Exp Lisc' or dbo.AR_CUSTOMER_LICENSE.UDF_CERT_ON_FILE='N' or dbo.AR_CUSTOMER_LICENSE.TERMSCODE='00' OR ((dbo.COD_NJ.License=dbo.AR_CUSTOMER_LICENSE.License OR dbo.COD_NY.License=dbo.AR_CUSTOMER_LICENSE.License) AND dbo.AR_CUSTOMER_LICENSE.TERMSCODE='30')OR (dbo.AR_CUSTOMER_LICENSE.TERMSCODE='30' AND dbo.AR_CUSTOMER_LICENSE.CREDITHOLD='Y') or dbo.AR_CUSTOMER_LICENSE.TERMSCODE='05' or dbo.AR_CUSTOMER_LICENSE.TERMSCODE='10' or dbo.AR_CUSTOMER_LICENSE.TERMSCODE='95')
