/****** Object:  View [dbo].[COD_SalesOrders]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[COD_SalesOrders]
AS
SELECT     MAS_POL.dbo.SO_SALESORDERHEADER.SALESORDERNO, MAS_POL.dbo.SO_SALESORDERHEADER.ARDIVISIONNO, MAS_POL.dbo.SO_SALESORDERHEADER.CUSTOMERNO, 
                      MAS_POL.dbo.SO_SALESORDERHEADER.ORDERTYPE, MAS_POL.dbo.AR_CUSTOMER.TERMSCODE, MAS_POL.dbo.AR_CUSTOMER.CREDITHOLD, 'ORDERSTATUS'=
						Case
							When (MAS_POL.dbo.AR_CUSTOMER.CREDITHOLD='Y') and (MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='CRED' OR MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='O' OR MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='N') then 'H'
							When (MAS_POL.dbo.AR_CUSTOMER.CREDITHOLD='N') and (MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='CRED' OR MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='O' OR MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='N') and MAS_POL.dbo.SO_SALESORDERHEADER.UDF_REVIEW_PO='Y' and MAS_POL.dbo.SO_SALESORDERHEADER.UDF_REVIEW_COOP='Y' then 'O'
							When MAS_POL.dbo.SO_SALESORDERHEADER.UDF_REVIEW_PO='N' then 'H'
							When MAS_POL.dbo.SO_SALESORDERHEADER.UDF_REVIEW_COOP='N' then 'H'
						Else MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS
						End,
						'CancelReasonCode'=
						Case
							When (MAS_POL.dbo.AR_CUSTOMER.CREDITHOLD='Y') and (MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='CRED' or MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='PO' or MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='COOP' or MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='AM' OR MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='O' OR MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='N' OR ((MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='00' or MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='05' OR MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='10' OR MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='95') and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='')) then 'CRED'
							When (MAS_POL.dbo.AR_CUSTOMER.CREDITHOLD='N') and (MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='CRED' OR MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='O' OR MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='N') and MAS_POL.dbo.SO_SALESORDERHEADER.UDF_REVIEW_PO='Y' and MAS_POL.dbo.SO_SALESORDERHEADER.UDF_REVIEW_COOP='Y' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'AM' then ''
							When MAS_POL.dbo.SO_SALESORDERHEADER.UDF_REVIEW_PO='N' then 'PO'
							When MAS_POL.dbo.SO_SALESORDERHEADER.UDF_REVIEW_COOP='N' then 'COOP'
							Else MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE
						End,
						'CreditReview'=
						Case
							When (MAS_POL.dbo.AR_CUSTOMER.CREDITHOLD='Y') and ((MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'MO' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'BO' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'CO' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'AL' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'IN') or MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE = '') Then 'N'
						Else 'Y'
						End
					
FROM         MAS_POL.dbo.SO_SALESORDERHEADER INNER JOIN
                      MAS_POL.dbo.AR_CUSTOMER ON MAS_POL.dbo.SO_SALESORDERHEADER.ARDIVISIONNO = MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO AND 
                      MAS_POL.dbo.SO_SALESORDERHEADER.CUSTOMERNO = MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO
WHERE     MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO = '00' AND MAS_POL.dbo.SO_SalesOrderHeader.CancelReasonCode <>'BH' AND ((MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='O' OR MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS='N')OR(MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE <> 'MO' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE <> 'BO' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE <> 'IN')) and(MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='00' or (MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='30' and MAS_POL.dbo.AR_CUSTOMER.TERMSCODE <> MAS_POL.dbo.SO_SALESORDERHEADER.TERMSCODE) or (MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='30' and MAS_POL.dbo.SO_SALESORDERHEADER.TERMSCODE='30') or MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='10' or MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='05' OR MAS_POL.dbo.AR_CUSTOMER.TERMSCODE='95')
