/****** Object:  View [dbo].[MO_InventoryHeld]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[MO_InventoryHeld]
AS
SELECT     MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMCODE, Sum(MAS_POL.dbo.SO_SALESORDERDETAIL.QUANTITYORDERED) as QuantityHeld
FROM         MAS_POL.dbo.SO_SALESORDERHEADER INNER JOIN
                      MAS_POL.dbo.SO_SALESORDERDETAIL ON MAS_POL.dbo.SO_SALESORDERHEADER.SALESORDERNO = MAS_POL.dbo.SO_SALESORDERDETAIL.SALESORDERNO       
WHERE  MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMTYPE='1' and MAS_POL.dbo.SO_SALESORDERDETAIL.WAREHOUSECODE='000' and (MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='IN' or MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='MO')
GROUP BY MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMCODE
