/****** Object:  View [dbo].[MOBO_DepletedOrders]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[MOBO_DepletedOrders]
AS
SELECT     MAS_POL.dbo.SO_SALESORDERHEADER.SALESORDERNO
FROM         MAS_POL.dbo.SO_SALESORDERHEADER INNER JOIN
                      MAS_POL.dbo.SO_SALESORDERDETAIL ON MAS_POL.dbo.SO_SALESORDERHEADER.SALESORDERNO = MAS_POL.dbo.SO_SALESORDERDETAIL.SALESORDERNO
WHERE      ((MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE = 'MO' OR MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE = 'IN' OR MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE = 'BO')
			AND MAS_POL.dbo.SO_SALESORDERHEADER.ORDERDATE < GETDATE()-1)
			OR
			(MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE = 'BH' AND MAS_POL.dbo.SO_SALESORDERHEADER.DateUpdated < GETDATE()-45)
GROUP BY MAS_POL.dbo.SO_SALESORDERHEADER.SALESORDERNO
HAVING      (SUM(MAS_POL.dbo.SO_SALESORDERDETAIL.QUANTITYORDERED) = 0)
