/****** Object:  View [dbo].[OrderRun_InvoiceHeader]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[OrderRun_InvoiceHeader]
AS
SELECT     MAS_POL.dbo.SO_INVOICEHEADER.INVOICENO, MAS_POL.dbo.SO_INVOICEHEADER.SHIPTONAME, MAS_POL.dbo.so_INVOICEHEADER.SHIPTOCODE, MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOADDRESS1, 
                      MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOADDRESS2, MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOCITY, MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOSTATE, 
                      MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOZIPCODE, MAS_POL.dbo.SO_INVOICEHEADER.SHIPVIA, MAS_POL.dbo.SO_INVOICEHEADER.BILLTONAME, 
                      MAS_POL.dbo.SO_INVOICEHEADER.BILLTOADDRESS1, MAS_POL.dbo.SO_INVOICEHEADER.BILLTOADDRESS2, MAS_POL.dbo.SO_INVOICEHEADER.BILLTOCITY, 
                      MAS_POL.dbo.SO_INVOICEHEADER.BILLTOSTATE, MAS_POL.dbo.SO_INVOICEHEADER.BILLTOZIPCODE, MAS_POL.dbo.SO_INVOICEHEADER.INVOICEDATE, 
                      MAS_POL.dbo.SO_INVOICEHEADER.SALESPERSONNO, MAS_POL.dbo.SO_INVOICEHEADER.INVOICEDUEDATE, MAS_POL.dbo.SO_INVOICEHEADER.CUSTOMERNO, 
                      SUM(ROUND(MAS_POL.dbo.SO_INVOICEDETAIL.QUANTITYSHIPPED, 2)) AS TotalQuantityFDL, ROUND(SUM(MAS_POL.dbo.SO_INVOICEDETAIL.QUANTITYSHIPPED), 2) 
                      AS TotalQuantityPOL, COUNT(MAS_POL.dbo.SO_INVOICEDETAIL.LINESEQNO) AS ItemCount, MAS_POL.dbo.SO_INVOICEHEADER.COMMENT, 
                      MAS_POL.dbo.SO_INVOICEHEADER.NONTAXABLEAMT + MAS_POL.dbo.SO_INVOICEHEADER.FREIGHTAMT AS InvoiceAmt, MAS_POL.dbo.AR_CUSTOMER.UDF_CORP_NAME, 
                      MAS_POL.dbo.AR_CUSTOMER.UDF_LICENSE_NUM, ISNULL(MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_INSTRUCTIONS,'') AS UDF_DELIVERY_INSTRUCT,
                      MAS_POL.dbo.SO_INVOICEHEADER.UDF_SPECIAL_INSTRUCTIONS_TXT, mAS_POL.dbo.SO_INVOICEHEADER.UDF_NJ_COOP,
                      MAS_POL.dbo.AR_TERMSCODE.TERMSCODEDESC, MAS_POL.dbo.SO_INVOICEHEADER.BATCHNO, CASE WHEN MAS_POL.dbo.SO_INVOICEHEADER.UDF_GUARANTEED_AM = 'Y' THEN 'AM' ELSE '' END AS AM,
                      MAS_POL.dbo.SO_InvoiceHeader.UDF_IS_BH AS IS_BH,
					  CASE WHEN MAS_POL.dbo.SO_InvoiceHeader.UDF_CHECK_REQUIRED = 'Y' THEN 'COD' ELSE '' END AS COD
FROM         MAS_POL.dbo.SO_INVOICEHEADER INNER JOIN
                      MAS_POL.dbo.SO_INVOICEDETAIL ON MAS_POL.dbo.SO_INVOICEHEADER.INVOICENO = MAS_POL.dbo.SO_INVOICEDETAIL.INVOICENO INNER JOIN
                      MAS_POL.dbo.AR_CUSTOMER ON MAS_POL.dbo.SO_INVOICEHEADER.CUSTOMERNO = MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO AND 
                      MAS_POL.dbo.SO_INVOICEHEADER.ARDIVISIONNO = MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO INNER JOIN
                      MAS_POL.dbo.AR_TERMSCODE ON MAS_POL.dbo.SO_INVOICEHEADER.TERMSCODE = MAS_POL.dbo.AR_TERMSCODE.TERMSCODE INNER JOIN
                      MAS_POL.dbo.SO_SHIPTOADDRESS ON MAS_POL.dbo.SO_INVOICEHEADER.ARDIVISIONNO = MAS_POL.dbo.SO_SHIPTOADDRESS.ARDIVISIONNO AND 
                      MAS_POL.dbo.SO_INVOICEHEADER.CUSTOMERNO = MAS_POL.dbo.SO_SHIPTOADDRESS.CUSTOMERNO AND 
                      MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOCODE = MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTOCODE
GROUP BY MAS_POL.dbo.SO_INVOICEHEADER.INVOICENO, MAS_POL.dbo.SO_INVOICEHEADER.SHIPTONAME, MAS_POL.dbo.so_INVOICEHEADER.SHIPTOCODE, MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOADDRESS1, 
                      MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOADDRESS2, MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOCITY, MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOSTATE, 
                      MAS_POL.dbo.SO_INVOICEHEADER.SHIPTOZIPCODE, MAS_POL.dbo.SO_INVOICEHEADER.SHIPVIA, MAS_POL.dbo.SO_INVOICEHEADER.BILLTONAME, MAS_POL.dbo.SO_INVOICEHEADER.BILLTOADDRESS1, 
                      MAS_POL.dbo.SO_INVOICEHEADER.BILLTOADDRESS2, MAS_POL.dbo.SO_INVOICEHEADER.BILLTOCITY, MAS_POL.dbo.SO_INVOICEHEADER.BILLTOSTATE, 
                      MAS_POL.dbo.SO_INVOICEHEADER.BILLTOZIPCODE, MAS_POL.dbo.SO_INVOICEHEADER.INVOICEDATE, MAS_POL.dbo.SO_INVOICEHEADER.SALESPERSONNO, 
                      MAS_POL.dbo.SO_INVOICEHEADER.INVOICEDUEDATE, MAS_POL.dbo.SO_INVOICEHEADER.CUSTOMERNO, MAS_POL.dbo.SO_INVOICEHEADER.COMMENT, 
                      MAS_POL.dbo.SO_INVOICEHEADER.NONTAXABLEAMT, MAS_POL.dbo.SO_INVOICEHEADER.FREIGHTAMT, MAS_POL.dbo.AR_CUSTOMER.UDF_CORP_NAME, 
                      MAS_POL.dbo.AR_CUSTOMER.UDF_LICENSE_NUM, MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_INSTRUCTIONS, MAS_POL.dbo.SO_INVOICEHEADER.UDF_SPECIAL_INSTRUCTIONS_TXT, 
                      MAS_POL.dbo.SO_INVOICEHEADER.UDF_NJ_COOP, MAS_POL.dbo.AR_TERMSCODE.TERMSCODEDESC, MAS_POL.dbo.SO_INVOICEHEADER.BATCHNO, MAS_POL.dbo.SO_INVOICEHEADER.UDF_GUARANTEED_AM,
                      MAS_POL.dbo.SO_InvoiceHeader.UDF_IS_BH, MAS_POL.dbo.SO_InvoiceHeader.UDF_CHECK_REQUIRED 
