/****** Object:  View [dbo].[PortalShipping]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[PortalShipping]
AS
SELECT     MAS_POL.dbo.AR_CUSTOMER.ARDivisionNo,
		   MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO,
		   MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_MON +
		   MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_TUES + 
		   MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_WED + 
		   MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_THURS +
		   MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_FRI AS ShipDays,
		   MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_REGION_CODE AS Region,
		   IsNull(MAS_POL.dbo.AR_CUSTOMER.ShipMethod,'') AS ShipVia
FROM         MAS_POL.dbo.AR_CUSTOMER INNER JOIN
                      MAS_POL.dbo.SO_SHIPTOADDRESS ON MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO = MAS_POL.dbo.SO_SHIPTOADDRESS.ARDIVISIONNO AND 
                      MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO = MAS_POL.dbo.SO_SHIPTOADDRESS.CUSTOMERNO AND 
                      MAS_POL.dbo.AR_CUSTOMER.PRIMARYSHIPTOCODE = MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTOCODE
where MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_REGION_CODE <> ''
