/****** Object:  View [dbo].[Portal_Account_ItemHistory]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[Portal_Account_ItemHistory]
AS
SELECT     MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE, MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.ITEMCODE, MAS_POL.dbo.AR_INVOICEHISTORYHEADER.CUSTOMERNO, 
                      SUM(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.QUANTITYSHIPPED) AS QUANTITYSHIPPED, MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.UNITPRICE
FROM         MAS_POL.dbo.AR_INVOICEHISTORYDETAIL INNER JOIN
                      MAS_POL.dbo.AR_INVOICEHISTORYHEADER ON MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.INVOICENO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICENO AND 
                      MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.HEADERSEQNO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.HEADERSEQNO
WHERE     (MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE >= DATEADD(YEAR, - 2, GETDATE())) AND (MAS_POL.dbo.AR_INVOICEHISTORYHEADER.MODULECODE = 'S/O') AND
 (MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDIVISIONNO='00') AND MAS_POL.dbo.AR_InvoiceHistoryDetail.UnitPrice > 0
GROUP BY MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE, MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.ITEMCODE, MAS_POL.dbo.AR_INVOICEHISTORYHEADER.CUSTOMERNO, 
                      MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.UNITPRICE
HAVING      (SUM(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.QUANTITYSHIPPED) > 0)
