/****** Object:  View [dbo].[PortalWebAccountLastOrdered]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[PortalWebAccountLastOrdered]
AS
SELECT     MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO, MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO, MAX(INVOICEDATE) AS LastOrdered
FROM         MAS_POL.dbo.AR_CUSTOMER LEFT OUTER JOIN
                      MAS_POL.dbo.AR_INVOICEHISTORYHEADER ON MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDIVISIONNO AND 
                      MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.CUSTOMERNO
where INVOICETYPE='IN'
GROUP BY  MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO, MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO
