/****** Object:  View [dbo].[SO_InventoryHeld]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[SO_InventoryHeld]
AS
with orderunion as
(
SELECT     MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMCODE, Sum(Case When MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'BH' and MAS_POL.dbo.SO_SALESORDERDETAIL.UnitPrice > 0 then MAS_POL.dbo.SO_SALESORDERDETAIL.QUANTITYORDERED ELSE 0 End) as QuantityHeld,
			Sum(Case When MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE='BH' or MAS_POL.dbo.SO_SALESORDERDETAIL.UnitPrice = 0 then MAS_POL.dbo.SO_SALESORDERDETAIL.QUANTITYORDERED ELSE 0 End) as QuantityHeldBh, SUM(MAS_POL.dbo.SO_SALESORDERDETAIL.QUANTITYORDERED) AS RAW
FROM         MAS_POL.dbo.SO_SALESORDERHEADER INNER JOIN
                      MAS_POL.dbo.SO_SALESORDERDETAIL ON MAS_POL.dbo.SO_SALESORDERHEADER.SALESORDERNO = MAS_POL.dbo.SO_SALESORDERDETAIL.SALESORDERNO       
WHERE  MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMTYPE='1' and MAS_POL.dbo.SO_SALESORDERDETAIL.WAREHOUSECODE='000' and (MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS ='O' or MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS ='N' or (MAS_POL.dbo.SO_SALESORDERHEADER.ORDERSTATUS ='H' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'BO' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'AL' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'MO' and MAS_POL.dbo.SO_SALESORDERHEADER.CANCELREASONCODE<>'IN'))
GROUP BY MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMCODE

UNION

SELECT     d.ITEMCODE
		, Sum(d.QUANTITYORDERED) as QuantityHeld
		, 0 as QuantityHeldBh
		, SUM(d.QUANTITYORDERED) AS RAW
FROM         MAS_POL.dbo.SO_INVOICEHEADER h INNER JOIN
                      MAS_POL.dbo.SO_INVOICEDETAIL d ON h.INVOICENO = d.INVOICENO   
WHERE  d.ITEMTYPE='1' and d.WAREHOUSECODE='000' and h.SalesOrderNo = ''
GROUP BY d.ITEMCODE
)
SELECT ItemCode
	  , Sum(QuantityHeld) as QuantityHeld
	  , Sum(QuantityHeldBh) as QuantityHeldBh
	  ,Sum(RAW) as RAW
FROM orderunion
GROUP BY ItemCode
