/****** Object:  View [dbo].[SO_TopRepSales]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[SO_TopRepSales]
AS
SELECT     MAS_POL.dbo.AR_SALESPERSON.SALESPERSONNAME, MAS_POL.dbo.AR_INVOICEHISTORYHEADER.InvoiceDate AS TRANSACTIONDATE, 
                      SUM(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.QUANTITYSHIPPED) AS 'QUANTITYSHIPPED', COUNT(MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICENO) 
                      AS 'INVOICE_COUNT', SUM(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.EXTENSIONAMT) AS 'SALES'
FROM         MAS_POL.dbo.AR_INVOICEHISTORYHEADER INNER JOIN
                      MAS_POL.dbo.AR_SALESPERSON ON MAS_POL.dbo.AR_INVOICEHISTORYHEADER.SALESPERSONDIVISIONNO = MAS_POL.dbo.AR_SALESPERSON.SALESPERSONDIVISIONNO AND 
                      MAS_POL.dbo.AR_INVOICEHISTORYHEADER.SALESPERSONNO = MAS_POL.dbo.AR_SALESPERSON.SALESPERSONNO INNER JOIN
                      MAS_POL.dbo.AR_INVOICEHISTORYDETAIL ON MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICENO = MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.INVOICENO AND 
                      MAS_POL.dbo.AR_INVOICEHISTORYHEADER.HEADERSEQNO = MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.HEADERSEQNO
WHERE     (MAS_POL.dbo.AR_INVOICEHISTORYHEADER.MODULECODE = 'S/O') AND (MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDIVISIONNO = '00' OR MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDIVISIONNO = '02') AND 
                      (MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICETYPE = 'IN')
GROUP BY MAS_POL.dbo.AR_SALESPERSON.SALESPERSONNAME, MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE
