/****** Object:  View [dbo].[Web_Orders_Coops]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[Web_Orders_Coops]
AS
SELECT                MAS_POL.dbo.SO_SALESORDERHEADER.SHIPEXPIREDATE AS SHIPDATE, 
                      SUM(MAS_POL.dbo.SO_SALESORDERDETAIL.QUANTITYORDERED) AS QUANTITYORDERED,
                      MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP as 'CoopNo'
                      /* CASE WHEN IsNumeric(MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP)=1 AND CHARINDEX('.',MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP)=0 THEN CAST(MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP AS INT) ELSE NULL END as 'CoopNo' */		
FROM         MAS_POL.dbo.SO_SALESORDERHEADER WITH ( NOLOCK ) INNER JOIN
                      MAS_POL.dbo.SO_SALESORDERDETAIL WITH ( NOLOCK ) ON MAS_POL.dbo.SO_SALESORDERHEADER.SALESORDERNO = MAS_POL.dbo.SO_SALESORDERDETAIL.SALESORDERNO
                      
WHERE     MAS_POL.dbo.SO_SALESORDERHEADER.ORDERTYPE='S' and (MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMTYPE = 1) and MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP <> '' and MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP <> 'None'
/* WHERE     MAS_POL.dbo.SO_SALESORDERHEADER.ORDERTYPE='S' and (MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMTYPE = 1) AND IsNumeric(MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP)=1  and CHARINDEX('.',MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP)=0 */
GROUP BY SHIPEXPIREDATE, UDF_NJ_COOP
