/****** Object:  View [dbo].[Web_Account_LastOrdered]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[Web_Account_LastOrdered]
AS
SELECT     MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO AS ARDIVISIONNO, MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO AS CUSTOMERNO, MAX(MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE) AS LastOrdered
FROM         MAS_POL.dbo.AR_CUSTOMER LEFT OUTER JOIN
                      MAS_POL.dbo.AR_INVOICEHISTORYHEADER ON MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDIVISIONNO AND 
                      MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.CUSTOMERNO
where MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICETYPE='IN'
GROUP BY MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO, MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO
