/****** Object:  View [dbo].[Web_Account_Items_Base_old]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[Web_Account_Items_Base_old]
AS
SELECT     ISNULL(MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDivisionNo,'') AS ARDIVISIONNO, ISNULL(MAS_POL.dbo.AR_INVOICEHISTORYHEADER.CUSTOMERNO,'') AS CUSTOMERNO,ISNULL(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.ITEMCODE,'') AS ITEMCODE, MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE, SUM(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.QUANTITYSHIPPED) AS QuantityShipped, MIN(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.UNITPRICE) as Price
FROM         MAS_POL.dbo.AR_INVOICEHISTORYDETAIL INNER JOIN
                      MAS_POL.dbo.AR_INVOICEHISTORYHEADER ON MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.INVOICENO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICENO AND 
                      MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.HEADERSEQNO = MAS_POL.dbo.AR_INVOICEHISTORYHEADER.HEADERSEQNO INNER JOIN
                      MAS_POL.dbo.CI_ITEM ON MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.ITEMCODE = MAS_POL.dbo.CI_ITEM.ITEMCODE
WHERE     (MAS_POL.dbo.CI_ITEM.ITEMTYPE = '1') AND (MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE >= DATEADD(YEAR, - 2, GETDATE())) AND (MAS_POL.dbo.AR_INVOICEHISTORYHEADER.MODULECODE='S/O') AND (MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDIVISIONNO = '00' or MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDIVISIONNO = '02')
GROUP BY MAS_POL.dbo.AR_INVOICEHISTORYHEADER.ARDivisionNo, MAS_POL.dbo.AR_INVOICEHISTORYHEADER.CUSTOMERNO,MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.ITEMCODE, MAS_POL.dbo.AR_INVOICEHISTORYHEADER.INVOICEDATE
HAVING SUM(MAS_POL.dbo.AR_INVOICEHISTORYDETAIL.QUANTITYSHIPPED)>0
