/****** Object:  View [dbo].[Web_Account_List]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[Web_Account_List]
AS
SELECT     CASE WHEN MAS_POL.dbo.AR_CUSTOMER.UDF_CUST_ACTIVE_STAT <> 'Y' THEN 'INACTIVE'
				WHEN Year(MAS_POL.dbo.AR_CUSTOMER.UDF_LIC_EXPIRATION)>1900 and MAS_POL.dbo.AR_CUSTOMER.UDF_LIC_EXPIRATION < GETDATE() THEN 'EXPIRED'
				WHEN MAS_POL.dbo.AR_CUSTOMER.TERMSCODE = '00' OR MAS_POL.dbo.AR_CUSTOMER.TERMSCODE = '05' OR MAS_POL.dbo.AR_CUSTOMER.TERMSCODE = '10' OR MAS_POL.dbo.AR_CUSTOMER.TERMSCODE = '95' THEN 'COD'
				WHEN (MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY1 + MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY2 + MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY3 + MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY4) > 0 THEN 'PAST DUE'
				ELSE '' END AS Status,
			MAS_POL.dbo.AR_CUSTOMER.ARDivisionNo, 
			MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO AS [Acct. #], 
            MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNAME AS [Account Name],
            MAS_POL.dbo.AR_CUSTOMER.UDF_WINE_BUYER AS Winebuyer,
            MAS_POL.dbo.AR_CUSTOMER.UDF_WINE_BUYER_2 AS Winebuyer2,
            MAS_POL.dbo.AR_CUSTOMER.UDF_WINE_BUYER_3 AS Winebuyer3,
            MAS_POL.dbo.AR_CUSTOMER.UDF_WINE_BUYER_PHONE AS [Winebuyer Phone],
            MAS_POL.dbo.AR_CUSTOMER.UDF_WINE_BUYER_PHONE_2 AS [Winebuyer2 Phone],
            MAS_POL.dbo.AR_CUSTOMER.UDF_WINE_BUYER_PHONE_3 AS [Winebuyer3 Phone],
            MAS_POL.dbo.AR_CUSTOMER.UDF_WINE_BUYER_EMAIL AS [Winebuyer Email],
            MAS_POL.dbo.AR_CUSTOMER.UDF_WINE_BUYER_2_EMAIL AS [Winebuyer2 Email],
            MAS_POL.dbo.AR_CUSTOMER.UDF_WINE_BUYER_3_EMAIL AS [Winebuyer3 Email],
            MAS_POL.dbo.AR_TERMSCODE.TERMSCODEDESC AS Terms,
            IsNull(MAS_POL.dbo.AR_CUSTOMER.CURRENTBALANCE+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY1+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY2+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY3+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY4,0) AS Balance,
            CASE WHEN (MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY1+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY2+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY3+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY4)<=0 THEN 0
                ELSE(MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY1+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY2+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY3+MAS_POL.dbo.AR_CUSTOMER.AGINGCATEGORY4) END AS PastDue,
            MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_INSTRUCTIONS AS [Delivery Notes],
            CASE WHEN MAS_POL.dbo.AR_CUSTOMER.UDF_PO_REQUIRED = 'Y' THEN 'x' ELSE '' END AS [PO Required],
            MAS_POL.dbo.AR_CUSTOMER.UDF_NJ_COOP AS [COOP #],
            MAS_POL.dbo.AR_CUSTOMER.SALESPERSONNO AS Salesperson, 
            MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTONAME AS 'Name (Ship To)',
            LTRIM(REPLACE(MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTOADDRESS1+CHAR(13)+CHAR(10)+MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTOADDRESS2
				+CHAR(13)+CHAR(10)+MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTOCITY+ ', '+MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTOSTATE+' '
				+MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTOZIPCODE,CHAR(13)+CHAR(10)+CHAR(13)+CHAR(10),CHAR(13)+CHAR(10))) as 'Address',
            MAS_POL.dbo.AR_CUSTOMER.UDF_ACCOUNT_TYPE AS 'Account Type', 
            MAS_POL.dbo.AR_CUSTOMER.UDF_AFFILIATIONS AS 'Affiliations',
            MAS_POL.dbo.AR_CUSTOMER.UDF_GROWTH_POTENTIAL AS 'Growth Potential', 
            MAS_POL.dbo.AR_CUSTOMER.UDF_STORE_REST_FOCUS AS 'Wine Focus',
            MAS_POL.dbo.AR_CUSTOMER.UDF_OTHER_KEY_SUPPLIERS AS 'Key Suppliers',
            MAS_POL.dbo.AR_UDT_SHIPPING.UDF_TERRITORY as 'Territory',
            CASE WHEN SUBSTRING(MAS_POL.dbo.AR_CUSTOMER.CUSTOMERTYPE,3,2)='ON' THEN 'On' ELSE 'Off' END AS 'Premise',
            MAS_POL.dbo.AR_CUSTOMER.SHIPMETHOD AS 'ShipMethod',
            IsNull(CASE WHEN YEAR(MAS_POL.dbo.AR_CUSTOMER.UDF_LIC_EXPIRATION)>1900 THEN MAS_POL.dbo.AR_CUSTOMER.UDF_LIC_EXPIRATION ELSE '12/31/9999' END,'12/31/1999') AS 'LicExp',
            MAS_POL.dbo.AR_CUSTOMER.UDF_CERT_ON_FILE AS 'IsCertOnFile',
            MAS_POL.dbo.AR_CUSTOMER.UDF_PERM_SPEC_DELIV AS 'IsPermDelInstr',
            MAS_POL.dbo.AR_CUSTOMER.CREDITHOLD AS 'IsOnCreditHold',
            IsNull(MAS_POL.dbo.AR_CUSTOMER.OPENORDERAMT,0) as 'OpenOrderAmt',
            MAS_POL.dbo.AR_CUSTOMER.UDF_LICENSE_NUM as 'License',
            dbo.Web_Account_LastOrdered.LastOrdered as LastOrdered,
            MAS_POL.dbo.SO_ShipToAddress.ShipToCity as 'City',
            MAS_POL.dbo.AR_UDT_SHIPPING.UDF_COUNTY as 'County',
			MAS_POL.dbo.AR_Customer.SHIPMETHOD as 'ShipVia'
from MAS_POL.dbo.AR_CUSTOMER INNER JOIN
                      MAS_POL.dbo.AR_TERMSCODE ON MAS_POL.dbo.AR_CUSTOMER.TERMSCODE = MAS_POL.dbo.AR_TERMSCODE.TERMSCODE INNER JOIN
                      MAS_POL.dbo.AR_SALESPERSON ON MAS_POL.dbo.AR_CUSTOMER.SALESPERSONDIVISIONNO = MAS_POL.dbo.AR_SALESPERSON.SALESPERSONDIVISIONNO AND 
                      MAS_POL.dbo.AR_CUSTOMER.SALESPERSONNO = MAS_POL.dbo.AR_SALESPERSON.SALESPERSONNO INNER JOIN
                      MAS_POL.dbo.SO_SHIPTOADDRESS ON MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO = MAS_POL.dbo.SO_SHIPTOADDRESS.ARDIVISIONNO AND 
                      MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO = MAS_POL.dbo.SO_SHIPTOADDRESS.CUSTOMERNO AND
                      MAS_POL.dbo.AR_CUSTOMER.PRIMARYSHIPTOCODE = MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTOCODE INNER JOIN
                      MAS_POL.dbo.AR_UDT_SHIPPING ON MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_REGION_CODE = MAS_POL.dbo.AR_UDT_SHIPPING.UDF_REGION_CODE LEFT OUTER JOIN
                      dbo.Web_Account_LastOrdered ON MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO = dbo.Web_Account_LastOrdered.CUSTOMERNO AND MAS_POL.dbo.AR_CUSTOMER.ARDivisionNo = dbo.Web_Account_LastOrdered.ARDivisionNo 
--WHERE     (MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO = '00') AND (MAS_POL.dbo.AR_CUSTOMER.SALESPERSONNO NOT LIKE '%XX%')
WHERE     (MAS_POL.dbo.AR_CUSTOMER.SALESPERSONNO NOT LIKE 'XX%')
