/****** Object:  View [dbo].[Web_Account_Items_Base]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[Web_Account_Items_Base]
AS
SELECT     ISNULL(POL.dbo.AR_INVOICEHISTORYHEADER_Union.ARDivisionNo,'') AS ARDIVISIONNO, ISNULL(POL.dbo.AR_INVOICEHISTORYHEADER_Union.CUSTOMERNO,'') AS CUSTOMERNO,ISNULL(POL.dbo.AR_INVOICEHISTORYDETAIL_Union.ITEMCODE,'') AS ITEMCODE, POL.dbo.AR_INVOICEHISTORYHEADER_Union.INVOICEDATE, SUM(POL.dbo.AR_INVOICEHISTORYDETAIL_Union.QUANTITYSHIPPED) AS QuantityShipped, MIN(POL.dbo.AR_INVOICEHISTORYDETAIL_Union.UNITPRICE) as Price
FROM         POL.dbo.AR_INVOICEHISTORYDETAIL_Union INNER JOIN
                      POL.dbo.AR_INVOICEHISTORYHEADER_Union ON POL.dbo.AR_INVOICEHISTORYDETAIL_Union.INVOICENO = POL.dbo.AR_INVOICEHISTORYHEADER_Union.INVOICENO AND 
                      POL.dbo.AR_INVOICEHISTORYDETAIL_Union.HEADERSEQNO = POL.dbo.AR_INVOICEHISTORYHEADER_Union.HEADERSEQNO INNER JOIN
                      MAS_POL.dbo.CI_ITEM ON POL.dbo.AR_INVOICEHISTORYDETAIL_Union.ITEMCODE = MAS_POL.dbo.CI_ITEM.ITEMCODE
WHERE     (MAS_POL.dbo.CI_ITEM.ITEMTYPE = '1') AND (POL.dbo.AR_INVOICEHISTORYHEADER_Union.INVOICEDATE >= DATEADD(YEAR, - 2, GETDATE())) AND (POL.dbo.AR_INVOICEHISTORYHEADER_Union.ARDIVISIONNO = '00' or POL.dbo.AR_INVOICEHISTORYHEADER_Union.ARDIVISIONNO = '02')
GROUP BY POL.dbo.AR_INVOICEHISTORYHEADER_Union.ARDivisionNo, POL.dbo.AR_INVOICEHISTORYHEADER_Union.CUSTOMERNO,POL.dbo.AR_INVOICEHISTORYDETAIL_Union.ITEMCODE, POL.dbo.AR_INVOICEHISTORYHEADER_Union.INVOICEDATE
HAVING SUM(POL.dbo.AR_INVOICEHISTORYDETAIL_Union.QUANTITYSHIPPED)>0
