/****** Object:  View [dbo].[Web_Account_Shipping]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW [dbo].[Web_Account_Shipping]
AS
SELECT     MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO AS CUSTOMERNO,
		   MAS_POL.dbo.AR_CUSTOMER.ARDivisionNo AS ARDivisionNo,
		   IsNull(CAST(CASE WHEN MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_MON='Y' THEN 1 ELSE 0 END AS BIT),1) AS DELIVERY_MON,
		   IsNull(CAST(CASE WHEN MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_TUES='Y' THEN 1 ELSE 0 END AS BIT),1) AS DELIVERY_TUES, 
		   IsNull(CAST(CASE WHEN MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_WED='Y' THEN 1 ELSE 0 END AS BIT),1) AS DELIVERY_WED, 
		   IsNull(CAST(CASE WHEN MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_THURS='Y' THEN 1 ELSE 0 END AS BIT),1) AS DELIVERY_THURS, 
		   IsNull(CAST(CASE WHEN MAS_POL.dbo.SO_SHIPTOADDRESS.UDF_DELIVERY_FRI='Y' THEN 1 ELSE 0 END AS BIT),1) AS DELIVERY_FRI
FROM         MAS_POL.dbo.AR_CUSTOMER INNER JOIN
                      MAS_POL.dbo.SO_SHIPTOADDRESS ON MAS_POL.dbo.AR_CUSTOMER.ARDIVISIONNO = MAS_POL.dbo.SO_SHIPTOADDRESS.ARDIVISIONNO AND 
                      MAS_POL.dbo.AR_CUSTOMER.CUSTOMERNO = MAS_POL.dbo.SO_SHIPTOADDRESS.CUSTOMERNO AND 
                      MAS_POL.dbo.AR_CUSTOMER.PRIMARYSHIPTOCODE = MAS_POL.dbo.SO_SHIPTOADDRESS.SHIPTOCODE
