version: "3"
services:
  pol-sql:
    image: polaner/sql-pol-db:v1
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TestP@ssw0rd"
    ports:
      - "14330:1433"
    volumes:
      - ./files:c:\data:ro