/****** Object:  Procedure [dbo].[PortalWebCoopProc]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [dbo].[PortalWebCoopProc]
	-- Add the parameters for the stored procedure here
AS
BEGIN
SET NOCOUNT ON
SELECT Main = (SELECT CONVERT(varchar,MAS_POL.dbo.SO_SALESORDERHEADER.SHIPEXPIREDATE,23) AS Date 
                      ,CONVERT(DECIMAL(9,2),(ROUND(SUM(MAS_POL.dbo.SO_SALESORDERDETAIL.QUANTITYORDERED),2))) AS Qty
                      ,MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP as Coop
FROM         MAS_POL.dbo.SO_SALESORDERHEADER INNER JOIN
                      MAS_POL.dbo.SO_SALESORDERDETAIL ON MAS_POL.dbo.SO_SALESORDERHEADER.SALESORDERNO = MAS_POL.dbo.SO_SALESORDERDETAIL.SALESORDERNO
                      
WHERE     MAS_POL.dbo.SO_SALESORDERHEADER.ORDERTYPE='S' and (MAS_POL.dbo.SO_SALESORDERDETAIL.ITEMTYPE = 1) and MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP <> '' and MAS_POL.dbo.SO_SALESORDERHEADER.UDF_NJ_COOP <> 'None'
GROUP BY SHIPEXPIREDATE, UDF_NJ_COOP
FOR JSON PATH
)
FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
END
